"""add webhook_event table

Revision ID: e47faf36f565
Revises: b2aaf0e82e61
Create Date: 2026-02-14 00:18:12.816834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e47faf36f565'
down_revision: Union[str, Sequence[str], None] = 'b2aaf0e82e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhookevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('lemon_order_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhookevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhookevent_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhookevent_lemon_order_id'), ['lemon_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhookevent_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhookevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhookevent_status'))
        batch_op.drop_index(batch_op.f('ix_webhookevent_lemon_order_id'))
        batch_op.drop_index(batch_op.f('ix_webhookevent_event_name'))

    op.drop_table('webhookevent')
    # ### end Alembic commands ###
